"""Shared constants for the PalmGuard AI training/inference pipeline.

Dataset structure (docs/AI_MODEL.md#dataset — source/licensing still
DECISION REQUIRED; size and split are now decided, see DATASET_TARGET_SIZE
below; this only fixes the on-disk convention):

    ai/data/raw/<CLASS_NAME>/*.jpg      # one folder per class, user-supplied images
    ai/data/splits/train/<CLASS_NAME>/*.jpg   # generated by src/dataset.py::split_dataset
    ai/data/splits/val/<CLASS_NAME>/*.jpg
    ai/data/splits/test/<CLASS_NAME>/*.jpg

CLASS_NAMES order is significant: it defines the softmax output index
used everywhere else (dataset labels, evaluation, prediction).
"""

from pathlib import Path

# Folder-name convention for ai/data/raw/<CLASS_NAME>/ and the model's own
# class order. This is a display/folder-naming choice local to the training
# pipeline — it's a different casing than docs/DATABASE.md's disease_classes.code
# (HEALTHY/BROWN_SPOT/WHITE_SCALE, all-caps), but that's fine:
# app/crud/disease.py::get_by_code() upper()s its input before matching, so
# "Brown_Spot" and "BROWN_SPOT" resolve to the same DB row either way.
#
# 3 classes, alphabetical order — matches the class order Keras'
# image_dataset_from_directory infers by default from ai/data/raw/<CLASS_NAME>/
# subfolder names, which is how models/mobilenetv2-v1.0.keras was trained.
# NON_PALM is NOT one of them: this model was trained on the 3 real disease
# classes only (matching the original research-proposal scope) and has no
# rejection class for "this isn't a palm leaf" — MIN_CONFIDENCE_THRESHOLD
# below is the only backstop for an out-of-distribution photo (see
# docs/AI_MODEL.md#confidence). The Gemini path (app/services/ai_inference.py)
# still has an explicit NON_PALM class; retraining this model with a 4th
# Non_Palm class (matching disease_classes in docs/DATABASE.md) is future work.
CLASS_NAMES = ["Brown_Spot", "Healthy", "White_Scale"]
NUM_CLASSES = len(CLASS_NAMES)

IMG_SIZE = (224, 224)  # MobileNetV2 default input size
BATCH_SIZE = 32

AI_DIR = Path(__file__).resolve().parent
RAW_DATA_DIR = AI_DIR / "data" / "raw"
SPLITS_DIR = AI_DIR / "data" / "splits"
MODELS_DIR = AI_DIR / "models"

# Train/Val/Test split — see docs/AI_MODEL.md#train--validation--test.
# Decided: 70/15/15 stratified across a 4,000-image target dataset.
SPLIT_RATIOS = {"train": 0.70, "val": 0.15, "test": 0.15}
SPLIT_SEED = 42

# Target dataset size (docs/AI_MODEL.md#dataset) — 4,000 images total,
# split per SPLIT_RATIOS above. Per-class image counts within that total
# are still DECISION REQUIRED.
DATASET_TARGET_SIZE = {"train": 2800, "val": 600, "test": 600}

# Transfer learning phase (frozen MobileNetV2 base).
HEAD_EPOCHS = 15
HEAD_LEARNING_RATE = 1e-3

# Fine-tuning phase (unfreeze top layers of the base at a low LR).
# See docs/AI_MODEL.md#fine-tuning — exact layer count/LR marked
# DECISION REQUIRED; defaults below are a reasonable starting point.
FINE_TUNE_EPOCHS = 10
FINE_TUNE_LEARNING_RATE = 1e-5
FINE_TUNE_UNFREEZE_LAYERS = 30  # unfreeze this many layers counting from the top

EARLY_STOPPING_PATIENCE = 5

MODEL_VERSION = "v1.3"  # docs/AI_MODEL.md#model-versioning: mobilenetv2-vX.Y

# A low top-1 softmax probability across all 3 trained classes means the
# photo is too blurry/ambiguous (or not a palm leaf at all, since this model
# has no NON_PALM class — see CLASS_NAMES above) to trust the argmax result.
# src/predict.py rejects that case as UNKNOWN rather than forcing whichever
# class happened to score highest. Threshold is a starting point, not tuned
# against a held-out validation set from this exact model's training run.
UNKNOWN_CLASS_CODE = "UNKNOWN"
MIN_CONFIDENCE_THRESHOLD = 0.75
